language: node_js

# Travis-CI Caching
cache:
  directories:
  - node_modules

before_install:
  - cd RepairVue

# S: Build Lifecycle
install:
  - npm install

before_script:


script:
  - npm run build

